import {
  ActionRequestSchema,
  AgentHandoffSchema,
  AgentSchema,
  ApprovalSchema,
  AuditEventSchema,
  CapabilityGrantSchema,
  PolicySchema,
} from "@/domain/schemas";

const agents = [
  {
    id: "agt_finance",
    name: "Finance Agent",
    jobDescription: "Reconcile invoices and prepare bounded vendor payments.",
    managerId: "usr_maya",
    managerName: "Maya Chen",
    status: "active",
    riskTier: "high",
    permissions: ["capped_payment"],
    lastActiveAt: "2026-07-31T12:52:00.000Z",
  },
  {
    id: "agt_vendor",
    name: "Vendor Agent",
    jobDescription: "Verify vendor identity, evidence, and payment readiness.",
    managerId: "usr_omar",
    managerName: "Omar Haddad",
    status: "active",
    riskTier: "medium",
    permissions: [],
    lastActiveAt: "2026-07-31T12:47:00.000Z",
  },
  {
    id: "agt_operations",
    name: "Operations Agent",
    jobDescription: "Coordinate approved SaaS and operational workflows.",
    managerId: "usr_maya",
    managerName: "Maya Chen",
    status: "active",
    riskTier: "medium",
    permissions: ["capped_payment"],
    lastActiveAt: "2026-07-31T12:39:00.000Z",
  },
  {
    id: "agt_deployment",
    name: "Deployment Agent",
    jobDescription: "Prepare staging releases without production credentials.",
    managerId: "usr_nora",
    managerName: "Nora Singh",
    status: "paused",
    riskTier: "high",
    permissions: [],
    lastActiveAt: "2026-07-30T16:18:00.000Z",
  },
].map((agent) => AgentSchema.parse(agent));

const policies = [
  {
    id: "pol_vendor_payment",
    name: "Approved vendor payment",
    description: "Allowlisted operating-account payments with two-person review.",
    version: 3,
    actionKind: "capped_payment",
    status: "active",
    constraints: {
      currency: "USD",
      maxAmountMinor: 500_000,
      approvedCounterpartyIds: ["cpty_acme", "cpty_stripe", "cpty_figma"],
      resource: "treasury:operating",
      validFrom: "2026-07-01T00:00:00.000Z",
      validUntil: "2026-10-01T00:00:00.000Z",
      capabilityTtlSeconds: 300,
    },
    approvalRule: {
      threshold: 2,
      approverIds: ["usr_maya", "usr_omar", "usr_nora"],
    },
  },
  {
    id: "pol_incident_payment",
    name: "Incident response payment",
    description: "Small emergency payments to pre-vetted response vendors.",
    version: 1,
    actionKind: "capped_payment",
    status: "active",
    constraints: {
      currency: "USD",
      maxAmountMinor: 75_000,
      approvedCounterpartyIds: ["cpty_pager"],
      resource: "treasury:incident",
      validFrom: "2026-07-01T00:00:00.000Z",
      validUntil: "2026-08-15T00:00:00.000Z",
      capabilityTtlSeconds: 120,
    },
    approvalRule: {
      threshold: 1,
      approverIds: ["usr_maya", "usr_nora"],
    },
  },
  {
    id: "pol_marketplace_pilot",
    name: "Marketplace pilot",
    description: "Proposed low-value marketplace settlement policy.",
    version: 1,
    actionKind: "capped_payment",
    status: "draft",
    constraints: {
      currency: "USD",
      maxAmountMinor: 25_000,
      approvedCounterpartyIds: ["cpty_marketplace"],
      resource: "treasury:pilot",
      validFrom: "2026-08-15T00:00:00.000Z",
      validUntil: "2026-10-15T00:00:00.000Z",
      capabilityTtlSeconds: 60,
    },
    approvalRule: {
      threshold: 1,
      approverIds: ["usr_omar"],
    },
  },
].map((policy) => PolicySchema.parse(policy));

const requests = [
  {
    id: "req_invoice_1048",
    type: "capped_payment",
    agentId: "agt_finance",
    policyId: "pol_vendor_payment",
    state: "pending_approval",
    input: {
      amountMinor: 184_200,
      currency: "USD",
      counterpartyId: "cpty_acme",
      counterpartyName: "Acme Cloud",
      resource: "treasury:operating",
      reference: "INV-1048",
    },
    policyEvaluation: {
      status: "requires_approval",
      reasonCodes: ["APPROVAL_REQUIRED"],
      requiredApprovals: 2,
      policyId: "pol_vendor_payment",
      policyVersion: 3,
      evaluatedAt: "2026-07-31T12:44:00.000Z",
    },
    createdAt: "2026-07-31T12:43:00.000Z",
    updatedAt: "2026-07-31T12:51:00.000Z",
  },
  {
    id: "req_stripe_0726",
    type: "capped_payment",
    agentId: "agt_finance",
    policyId: "pol_vendor_payment",
    state: "capability_issued",
    input: {
      amountMinor: 64_000,
      currency: "USD",
      counterpartyId: "cpty_stripe",
      counterpartyName: "Stripe",
      resource: "treasury:operating",
      reference: "JUL-PLATFORM",
    },
    policyEvaluation: {
      status: "requires_approval",
      reasonCodes: ["APPROVAL_REQUIRED"],
      requiredApprovals: 2,
      policyId: "pol_vendor_payment",
      policyVersion: 3,
      evaluatedAt: "2026-07-31T12:28:00.000Z",
    },
    createdAt: "2026-07-31T12:27:00.000Z",
    updatedAt: "2026-07-31T12:41:00.000Z",
  },
  {
    id: "req_atlas_2251",
    type: "capped_payment",
    agentId: "agt_finance",
    policyId: "pol_vendor_payment",
    state: "denied",
    input: {
      amountMinor: 725_000,
      currency: "USD",
      counterpartyId: "cpty_atlas",
      counterpartyName: "Atlas Systems",
      resource: "treasury:operating",
      reference: "INV-2251",
    },
    policyEvaluation: {
      status: "denied",
      reasonCodes: ["AMOUNT_EXCEEDS_LIMIT", "COUNTERPARTY_NOT_ALLOWED"],
      requiredApprovals: 0,
      policyId: "pol_vendor_payment",
      policyVersion: 3,
      evaluatedAt: "2026-07-31T12:18:00.000Z",
    },
    createdAt: "2026-07-31T12:17:00.000Z",
    updatedAt: "2026-07-31T12:18:00.000Z",
  },
  {
    id: "req_figma_0731",
    type: "capped_payment",
    agentId: "agt_operations",
    policyId: "pol_vendor_payment",
    state: "succeeded",
    input: {
      amountMinor: 12_900,
      currency: "USD",
      counterpartyId: "cpty_figma",
      counterpartyName: "Figma",
      resource: "treasury:operating",
      reference: "JUL-SEATS",
    },
    policyEvaluation: {
      status: "requires_approval",
      reasonCodes: ["APPROVAL_REQUIRED"],
      requiredApprovals: 2,
      policyId: "pol_vendor_payment",
      policyVersion: 3,
      evaluatedAt: "2026-07-31T11:49:00.000Z",
    },
    createdAt: "2026-07-31T11:48:00.000Z",
    updatedAt: "2026-07-31T12:05:00.000Z",
  },
].map((request) => ActionRequestSchema.parse(request));

const approvals = [
  {
    id: "apr_maya_1048",
    actionRequestId: "req_invoice_1048",
    approverId: "usr_maya",
    approverName: "Maya Chen",
    decision: "approved",
    reason: "Invoice and vendor evidence match.",
    createdAt: "2026-07-31T12:51:00.000Z",
  },
  {
    id: "apr_maya_stripe",
    actionRequestId: "req_stripe_0726",
    approverId: "usr_maya",
    approverName: "Maya Chen",
    decision: "approved",
    createdAt: "2026-07-31T12:34:00.000Z",
  },
  {
    id: "apr_omar_stripe",
    actionRequestId: "req_stripe_0726",
    approverId: "usr_omar",
    approverName: "Omar Haddad",
    decision: "approved",
    createdAt: "2026-07-31T12:39:00.000Z",
  },
].map((approval) => ApprovalSchema.parse(approval));

const capabilities = [
  {
    id: "cap_stripe_0726",
    actionRequestId: "req_stripe_0726",
    issuedToAgentId: "agt_finance",
    status: "active",
    scope: {
      actionKind: "capped_payment",
      resource: "treasury:operating",
      amountLimitMinor: 64_000,
      currency: "USD",
      counterpartyId: "cpty_stripe",
    },
    issuedAt: "2026-07-31T12:41:00.000Z",
    expiresAt: "2026-07-31T12:46:00.000Z",
  },
].map((capability) => CapabilityGrantSchema.parse(capability));

const auditEvents = [
  {
    id: "evt_approval_1048",
    organizationId: "org_agentos_demo",
    actionRequestId: "req_invoice_1048",
    actor: { type: "human", id: "usr_maya", displayName: "Maya Chen" },
    eventType: "approval.recorded",
    outcome: "allowed",
    summary: "Maya approved Acme Cloud invoice INV-1048.",
    metadata: { approvals: 1, required: 2 },
    occurredAt: "2026-07-31T12:51:00.000Z",
  },
  {
    id: "evt_capability_stripe",
    organizationId: "org_agentos_demo",
    actionRequestId: "req_stripe_0726",
    actor: {
      type: "system",
      id: "demo-vault",
      displayName: "Demo capability service",
    },
    eventType: "capability.issued",
    outcome: "allowed",
    summary: "Bounded demo capability issued for Stripe.",
    metadata: { ttlSeconds: 300, amountLimitMinor: 64000 },
    occurredAt: "2026-07-31T12:41:00.000Z",
  },
  {
    id: "evt_policy_atlas",
    organizationId: "org_agentos_demo",
    actionRequestId: "req_atlas_2251",
    actor: {
      type: "system",
      id: "policy-engine",
      displayName: "Policy engine",
    },
    eventType: "policy.evaluated",
    outcome: "denied",
    summary: "Atlas payment exceeded the cap and counterparty allowlist.",
    metadata: { policyVersion: 3, amountMinor: 725000 },
    occurredAt: "2026-07-31T12:18:00.000Z",
  },
  {
    id: "evt_executed_figma",
    organizationId: "org_agentos_demo",
    actionRequestId: "req_figma_0731",
    actor: {
      type: "agent",
      id: "agt_operations",
      displayName: "Operations Agent",
    },
    eventType: "action.executed",
    outcome: "allowed",
    summary: "Demo payment execution recorded for Figma seats.",
    metadata: { reference: "JUL-SEATS", amountMinor: 12900 },
    occurredAt: "2026-07-31T12:05:00.000Z",
  },
].map((event) => AuditEventSchema.parse(event));

const handoffs = [
  {
    id: "hnd_vendor_finance",
    fromAgentId: "agt_vendor",
    toAgentId: "agt_finance",
    actionRequestId: "req_invoice_1048",
    state: "delivered",
    dataClassification: "confidential",
    purpose: "Share verified vendor evidence for INV-1048.",
    createdAt: "2026-07-31T12:40:00.000Z",
    expiresAt: "2026-08-01T12:40:00.000Z",
  },
  {
    id: "hnd_finance_operations",
    fromAgentId: "agt_finance",
    toAgentId: "agt_operations",
    actionRequestId: "req_stripe_0726",
    state: "authorized",
    dataClassification: "restricted",
    purpose: "Hand off the approved Stripe payment execution context.",
    delegatedCapabilityId: "cap_stripe_0726",
    createdAt: "2026-07-31T12:42:00.000Z",
    expiresAt: "2026-07-31T12:46:00.000Z",
  },
].map((handoff) => AgentHandoffSchema.parse(handoff));

export const demoData = {
  agents,
  policies,
  requests,
  approvals,
  capabilities,
  auditEvents,
  handoffs,
};
